<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>


      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ecommerce.Domain\ecommerce.Domain.csproj" />
    </ItemGroup>
</Project>
